require "ruby_rpg"
require "singleton"
require "csv"

# Load in dependency order
require_relative "components/player_controller"
require_relative "player"
require_relative "scenery"
require_relative "map_tile"
require_relative "map"
require_relative "physics"
require_relative "physics/collider"
require_relative "physics/circle_collider"
require_relative "physics/rect_collider"
require_relative "physics/ray"
require_relative "physics/raycast_hit"
require_relative "physics/collision"
require_relative "physics/collisions/circle_circle"
require_relative "physics/collisions/rect_rect"
require_relative "physics/collisions/circle_rect"
require_relative "physics/collision_resolver"
